src/components/shared/ToggleButton.tsx
=> feat#7 : togglebutton 기능

src/components/shared/Badge.tsx
- 아이콘 왼쪽 위치 시 뱃지 구현
- 아이콘 오른쪽 위치 시 뱃지 구현
=> feat#2: Badge 컴포넌트 구현

src/components/shared/dropdown/dropdownLabel.tsx, src/components/shared/dropdown/dropdownOption.tsx, src/components/shared/dropdown/dropdownPanel.tsx, src/components/shared/dropdown/dropdownSelect.tsx, src/components/shared/dropdown/dropdownWrapper.tsx, src/components/shared/dropdown/index.tsx, src/components/shared/input/index.tsx, src/components/shared/input/inputCore.tsx, src/components/shared/input/inputCoreWrapper.tsx, src/components/shared/input/inputDuplicateCheck.tsx, src/components/shared/input/inputLabel.tsx, src/components/shared/input/inputMain.tsx, src/components/shared/input/inputValidatedText.tsx, src/components/shared/popup/index.tsx, src/components/shared/popup/popupContents.tsx, src/components/shared/popup/popupDimmedLayer.tsx, src/components/shared/popup/popupMain.tsx, src/components/shared/popup/popupTitle.tsx
#6 
- 추후 Popup에 대한 원활한 합성을 위해 일부 컴포넌트의 구조를 구현
- 향후 개발 시 사용 방법을 더 쉽게 조합하여 사용할 수 있도록 구조를 설계
- 유연성 확보를 위해, 컴포넌트의 사용 방법은 이를 사용할 개발자에게 위임 
- 컴포넌트 사용법은 TSDoc으로 상단에 작성해 두었습니다. 
- 컴포넌트를 불러와 마우스 호버 시 하단에 Doc이 표시됩니다.
=> [#6] Popup 및 Input, Dropdown 컴포넌트 구조설계

src/app/hun/page.tsx, src/components/shared/Card.tsx
=> feat #12 : Card 컴포넌트 제작

src/app/han/page.tsx, src/components/shared/Badge.tsx, src/components/shared/LoadingSpinner.tsx, src/components/shared/NewsListItem.tsx, src/components/shared/StockListItem.tsx
- 로딩 스피너 구현
- NewsListItem 커서 포인터 추가
- StockListItem 커서 포인터 추가
- Badge 텍스트 드래그 금지 추가 Close #11
=> [#11] 로딩 스피너 구현

src/app/(tmp)/hun/page.tsx, src/components/shared/Card.tsx, src/utils/Date.ts
- Card.tsx 내 코드 일부 수정
- day.js를 이용한 날짜 시간 계산 Date.ts 작성
Close #25
Card의 O초전, O분전, O시간전, O개월전, O년전 을 표시하기 위한 utils/Date.ts 생성
=> feat #25 : Card.tsx 수정 및 utils 날짜,시간계산

src/components/shared/Wrapper.tsx, src/components/shared/buttons/ButtonBase.tsx, src/components/shared/buttons/FabButton.tsx, src/components/shared/buttons/IconButton.tsx, src/components/shared/buttons/IconButtonBase.tsx, src/components/shared/buttons/LanguageButton.tsx, src/components/shared/buttons/TextButton.tsx, tailwind.config.ts
#27 
- button 컴포넌트 코드 수정
- tailwind.config button, shadow 커스텀 값 추가
- wrapper 컴포넌트 구현
- wrapper 컴포넌트 padding 값과 children 받아서 사용할 수 있도록 구현했는데 수정이 필요한 부분 말씀해주세요
- shadow 값 넣어봤는데 이상하면 말씀해주세요
=> Wrapper 컴포넌트구현

src/app/(tmp)/hun/page.tsx, src/components/shared/Card.tsx
- Card 컴포넌트 뉴스 2개로 수정
- Card Bg색상 변경 및 underline, cursor-pointer 추가
Close #34
- Card-3 뉴스 두개로 코드 수정
- Card-1, Card-2 bg색상 추가, underline, cursor-pointer 추가
=> feat #34 : Card 컴포넌트 수정

src/components/shared/Wrapper.tsx
- Wrapper컴포넌트  스타일 코드 수정
#37 
- Wrapper 컴포넌트 스타일 코드 수정
- 추가 요청사항 있다면 말씀해주세요!
=> refact 37# : Wrapper 컴포넌트 수정

src/app/(tmp)/hun/page.tsx, src/components/shared/Card.tsx
=> feat #39 : Card-3 분리

src/app/(tmp)/hun/page.tsx, src/components/shared/Card.tsx
=> bug #41 : Card css 수정

src/app/(after)/layout.tsx, src/app/(before)/layout.tsx, src/app/(landing)/layout.tsx
=> feat #36 : header

src/app/(after)/layout.tsx, src/app/(before)/layout.tsx
=> feat #49 : header zindex

src/app/(before)/find/id/page.tsx, src/app/(before)/login/page.tsx, src/components/shared/buttons/ButtonBase.tsx, src/components/shared/buttons/FabButton.tsx, src/components/shared/buttons/IconButton.tsx, src/components/shared/buttons/IconButtonBase.tsx, src/components/shared/buttons/LanguageButton.tsx, src/components/shared/buttons/TextButton.tsx, src/components/shared/buttons/types.ts
#50 
- button 컴포넌트에서 onClick 사용가능하도록 구현
- useInputChange 사용하여 form 유효성 검사 후 button 활성화 (수정 필요)
- 소셜회원이라면 찾은 id에 해당 소셜 로고 표시
- 로그인, 비밀번호 찾기페이지로 라우팅 기능
- button 컴포넌트에서 타입 또는 오류 발생시 커맨트 부탁드립니다
- 태그, 스타일 코드 겹치는 부분 리펙토링 필요
=> feat #50 : 아이디 찾기 페이지Ui 구현

src/app/(before)/@modal/(.)find/pw/modal/page.tsx, src/app/(before)/@modal/default.tsx, src/app/(before)/find/id/page.tsx, src/app/(before)/find/pw/page.tsx, src/app/(before)/layout.tsx
#59 
- Input.Validated 사용하여 input 작성
- 유효성 검사 성공 => router.push 사용하여 모달창 경로 이동
- 병렬, 인터셉팅 라우트를 사용 modal창 발생
- 모달창에서 로그인 버튼 클릭 시 로그인 페이지로
- 모달창은 닫기 위해 window.location.href 사용
- 인터셉팅 라우팅 처리로 인해 모달 경로에서 새로고침시 404가 발생합니다 나중에 페이지 에러 헨들링 필요!
=> feat #59 : 비밀번호 찾기 페이지UI 구현

src/app/(after)/home/page.tsx, src/components/recent/Recent.tsx, src/components/recent/RecentItem.tsx
- StockIcon Id, path 수정으로 인한 type추가
Close #57
- StockIcon Id, path 수정으로 인한 type추가
=> feat #57 : Stock type path, id 추가

src/app/loading.tsx, src/app/not-found.tsx
=> feature #62 : NotFound / 로딩 페이지 UI 구현

src/app/(after)/search/page.tsx, src/components/search/DeleteSearch.tsx, src/components/search/InputItem.tsx, src/components/search/NoSearchData.tsx, src/components/search/PopularItem.tsx, src/components/search/PopularSearch.tsx, src/components/search/RecentSearch.tsx, src/utils/date.ts
- 최근 검색어 데이터 없을시 UI
- 최근 검색어 데이터 있을시 UI
- 인기 검색어 UI
=> feat #64 : 발견 페이지 초기 화면 구현

package.json, src/components/news/RecentNews.tsx, yarn.lock
- react-intersection-observer 패키지 설치
- Recent News 컴포넌트 클라이언트 컴포넌트로 변경
- 무한 스크롤 구현
=> feat #72 : 최신뉴스 - 무한스크롤 기능 추가

src/components/shared/buttons/IconButton.tsx, src/components/shared/buttons/IconButtonBase.tsx, src/components/shared/buttons/TextButton.tsx, src/components/shared/buttons/types.ts
#77 
- base컴포넌트 'use client 사용
- disabled 일시 onClick 무효화
- IconButtonStyleTypes 추가
- TextButton, IconButton에서 'use client' 제거
- 
-오류 발생, 발견 시 커맨트 부탁드립니다
=> refact #77 : button컴포넌트 수정

src/app/(after)/home/page.tsx, src/components/favorite/FavoriteItem.tsx, src/components/favorite/FavoriteMain.tsx, src/constants.ts
=> feat #87 : Home 관심종목 UI 구현

src/app/(after)/layout.tsx, src/components/news/NewsDetail.tsx, src/components/shared/buttons/ButtonBase.tsx, src/components/shared/buttons/FabButton.tsx, src/components/shared/buttons/IconButton.tsx, src/components/shared/buttons/IconButtonBase.tsx, src/components/shared/buttons/LanguageButton.tsx, src/components/shared/buttons/TextButton.tsx, src/components/user/SectionBox.tsx
#91 
- base 컴포넌트 icon 타입 => ReactNode로 변경
- base 컴포넌트 ionClassName 삭제
- 추가 수정했습니다. 오류 발견 시 커맨트 부탁드립니다 ㅠ
=> refact # 91 : button 컴포넌트 수정

.gitignore, next.config.mjs, src/types/news.ts, src/utils/supabase/server.ts
=> feat #93 : supabase 함수 추가 types 폴더 추가

next.config.mjs, src/app/(after)/news/[id]/page.tsx, src/app/(after)/news/page.tsx, src/app/api/news/related/stock/[id]/route.ts, src/app/api/news/related/stock/route.ts, src/components/news/HomeRelatedNews.tsx, src/components/news/OriginNewsCard.tsx, src/components/news/RelatedStock.tsx, src/components/shared/Card.tsx, src/components/shared/NewsListItem.tsx, src/components/shared/StockIcon.tsx, src/components/shared/StockListItem.tsx, src/types/stock.ts
- 주식 logo 이미지 경로 환경설정 추가
- 관심종목과 관련된 뉴스
- 뉴스와 관련된 관심종목
- 주요 뉴스
- 오늘의 인기 있는 뉴스
- 주식 타입 정의
=> feat #95 : 뉴스 API 구현 1차 완료

src/components/news/NewsDetail.tsx, src/components/news/OriginNewsCard.tsx, src/components/shared/Card.tsx, src/components/shared/StockIcon.tsx, src/types/news.ts
- 썸네일 없을 시 아잇나우 로고 출력
- 주식 로고 없을 시 아잇나우 로고 출력
=> feat #95 : 썸네일/ 로고  없을 시 상황 추가

src/app/api/search/news/route.ts, src/app/api/search/stock/route.ts, src/components/search/FindNews.tsx, src/components/search/FindStock.tsx, src/components/search/FindStockItem.tsx, src/constants.ts
=> feat #104 : Search 주식, 뉴스 데이터 연결

src/app/api/search/news/route.ts, src/app/api/search/stock/route.ts, src/components/homefavorite/FavoriteItem.tsx, src/components/recent/RecentItem.tsx, src/components/search/FindNews.tsx, src/components/search/FindStock.tsx, src/components/search/FindStockItem.tsx, src/components/search/NewsItem.tsx, src/components/shared/Card.tsx
- api 호출 시 디바운스 추가
- search Stock, News api 호출 코드 수정
- Card Component내 Link 추가
- Link 중첩으로 인한 오류 메세지해결
Close #108
=> feat #108 : 디바운스,api 변경,  Card Link 추가 및 오류 수정

src/app/api/search/stock/route.ts
- api code 수정
column 명 code -> stock_code 변경으로 인한 api 코드 변화
=> refact : api code 수정

src/app/(after)/news/[id]/page.tsx, src/components/news/NewsDetail.tsx, src/components/skeleton/Skeleton.tsx, tailwind.config.ts
=> feat #114 : Skeleton UI Base

src/components/shared/StockIcon.tsx, src/components/shared/StockListItem.tsx
feat #118 : StockListItem type related UI 추가
`<StockListItem type="related" stocke={stock}/>`
과 같은 식으로 사용하시면 됩니다
=> feat #118 : StockListItem type related UI 추가

src/components/shared/StockListItem.tsx
=> fix #122 : 주가 소수점 미표기 수정

src/components/signup/SignupForm.tsx
=> refact #127 : 일반 회원가입 기능 수정

src/components/shared/StockListItem.tsx, src/components/skeleton/news/SkeletonHomeRelatedNews.tsx, src/components/skeleton/news/SkeletonNewsListItem.tsx, src/components/skeleton/news/SkeletonRelatedNewsToStock.tsx, src/components/skeleton/news/SkeletonTodayPopularNews.tsx, yarn.lock
- description 타입 UI 추가
- report 타입 UI 추가
=> feat #133 : StockListItem UI 추가

src/app/(after)/stock/interest/page.tsx, src/components/shared/chart/rechart/StockAIReportCore.tsx, src/components/stock/AddInterest.tsx, src/components/stock/RequestWrapper.tsx, src/components/stock/ShowingInterest.tsx, yarn.lock
- 회의 결정사항
- Infinite Scroll: react-intersection-observer 라이브러리 사용
- Virtual Scroll 구현 후 연동되지 않을 시 직접 개발 예정
- Virtual Scroll: 추후 도입, 프로젝트 1차 완성 우선
- 관심 주식 페이지 컴포넌트 분리
- RequestWrapper 컴포넌트 API 요청 방식 및 getInterest 함수 TSDoc
=> [#132] Infinite Scroll 추가 및 컴포넌트 관심사 분리

src/app/(after)/news/page.tsx, src/components/news/NewsBorder.tsx, src/components/news/RecentNews.tsx, src/components/shared/NewsListItem.tsx
=> refact #139 : 최신 뉴스 무한스크롤 렌더링 성능 개선

src/app/(after)/user/page.tsx, src/app/api/mypage/route.ts, src/app/api/user/route.ts, src/auth.ts, src/components/shared/Checkbox.tsx, src/components/signup/ProfileSetup.tsx, src/components/skeleton/mypage/SkeletonProfile.tsx, src/components/user/ProfileSection.tsx, src/middleware.ts, tsconfig.json
#148 
- 이전 merge 오류로 재 rebase merge 요청
- sessionContenxt 생성
- useSession으로 현재 로그인한 유저 정보 가져오기
- useSession loading 값에 따라 sseleton UI 적용
- next-auth.d.ts 로 User 타입 설정
- 프로필 수정 시 이전 이미지 supbase 스트로지에서 삭제
- 이미지 삭제를 위한 profileImgName 속성,컬럼 추가
- 이미지 파일 이름 변환 함수 생성
- checkbox display name 추가
- ref사용하여 nickname값 초기 설정 (수정 필요)
- 현재 useSession 을 사용해서 유저 정보를 가져온후 해당 정보를 참고해서 수정 중
- 유저 정보를 수정하였을 때 session을 초기화 하는 기능이 필요! (추가 작업 필요)
=> 유저 프로필 수정 기능

src/app/(after)/search/page.tsx, src/app/api/chatbot/route.ts, src/app/api/search/popular/route.ts, src/app/api/search/stock/route.ts, src/components/chatbot/ChatbotChat.tsx, src/components/chatbot/ChatbotContent.tsx, src/components/chatbot/ChatbotInput.tsx, src/components/chatbot/ChatbotItem.tsx, src/components/search/FindStockItem.tsx, src/components/search/InputItem.tsx, src/components/search/PopularSearch.tsx, src/components/search/SearchLabel.tsx, src/components/skeleton/search/SkeletonPopularStock.tsx, src/utils/llama.ts
- 챗봇 api 연결
- 챗봇 기능 추가
- 인기검색어 추가
Close #131
챗봇 프롬프팅은 추후 보완
=> feat #131 : 챗봇 기능 및 인기검색어

src/auth.ts
=> refact #157 :  next-auth 유저 session 데이터 수정

src/app/[locale]/(after)/stock/page.tsx, src/app/api/stock/decrease/route.ts, src/app/api/stock/increase/route.ts, src/app/api/stock/route.ts, src/components/stock/AllStocks.tsx, src/components/stock/LimitStocks.tsx
=> feat #164 : 주식 페이지 추가

src/app/[locale]/(after)/stock/page.tsx, src/components/skeleton/news/SkeletonRelatedStock.tsx, src/components/skeleton/stock/SkeletonLimitStocks.tsx, src/components/skeleton/stock/SkeletonStockListItem.tsx, src/components/stock/AllStocks.tsx, src/components/stock/LimitStocks.tsx
=> feat #168 : StockListItem 스켈레톤 구현

src/app/[locale]/(after)/news/[id]/page.tsx, src/app/api/news/[id]/route.ts, src/components/news/NewsDetail.tsx, src/components/shared/IntlClientProvider.tsx, src/components/shared/NewsListItem.tsx, src/constants.ts, src/utils/translate.ts
- getTranslatedNews
- hasTranslatedNews
- IntlClientProvider
=> refact #181 : 뉴스 번역 관련 로직 개선

src/app/api/news/[id]/route.ts
- 조회수 하루마다 증가
- news_iplog 테이블에 갱신
=> refact #184 : news 조회수 IP 기준 추가

src/app/api/home/recent/route.ts, src/components/recent/Recent.tsx, src/components/recent/RecentItem.tsx, src/components/shared/StockListItem.tsx, src/service/aightnowClient.ts
- Home 최근조회 추가
- StockListItem Link -> button 변경 및 조회등록 추가
=> feat #156 : Home 최근조회 추가

src/components/shared/StockListItem.tsx
=> fix #190 : StockListItem 스타일 수정

src/app/[locale]/(after)/news/[id]/page.tsx, src/app/api/news/related/stock/route.ts, src/components/news/HomeNewsTab.tsx, src/components/news/HomeRecentNews.tsx, src/components/news/HomeRelatedNews.tsx, src/components/news/ImportantNews.tsx, src/components/news/NewsDetail.tsx, src/components/news/RecentNews.tsx, src/components/news/RelatedNewsToStock.tsx, src/components/news/RelatedStock.tsx, src/components/news/TodayPopularNews.tsx, src/service/aightnowClient.ts
- 뉴스 리스트 불러오기 이전
- 뉴스 상세보기 이전
- 관련뉴스 불러오기 이전
- 관련 주식 불러오기 이전
=> refact #194 : fetch 로직 businessAPI로 이전

src/components/shared/ProfileDetails.tsx, src/components/signup/Agreement.tsx, src/components/signup/AgreementBox.tsx, src/components/signup/Auth.tsx, src/components/signup/ProfileImageEditor.tsx, src/components/signup/ProfileSetup.tsx, src/components/signup/SignupForm.tsx, src/components/user/CheckPassword.tsx, src/components/user/ModalWrapper.tsx, src/components/user/MyPageSection.tsx, src/components/user/MypageModals.tsx, src/components/user/ProfileUpdated.tsx, src/components/user/SectionBox.tsx, src/components/user/SidebarItem.tsx, src/components/user/TermsBox.tsx, src/components/user/UserAccountEdit.tsx, src/components/user/UserAccountForm.tsx, src/components/user/UserInfo.tsx, src/components/user/UserInfoList.tsx, src/components/user/UserProfile.tsx, src/constants.ts, src/hooks/user/useImageUpload.ts, src/hooks/user/useSessionData.ts, src/hooks/user/useStockSelection.ts
#189 
-  유저가 주식종목 선택후 값 변경/저장 시 유효하지않다면 값 삭제(수정 필요)
-  /api/search/stck  사용하여 종목 검색 구현
- supabase   interest_stock테이블 함수, 트리거 설정
- 유저 가입/수정 시  interest_stock테이블 데이터 추가 및 수정
- useStockSelection 훅 작성
- useImageUpload 훅 작성
- 컴포넌트 type 네이밍  수정
- 컴포넌트 export default  function 으로 변경
- 6개의 종목 외에 다른 값이 들어간다면 데이터베이스에 값이 들어가지 않도록했습니다(리펙토링 필요)
=> 유저 관심종목 추가/수정

messages/en.json, messages/fr.json, messages/ja.json, messages/ko.json, messages/zh.json
=> feature #199 : 국제화 날짜 데이터 추가

messages/en.json, messages/fr.json, messages/ja.json, messages/ko.json, messages/zh.json, src/app/[locale]/(after)/search/page.tsx, src/components/chatbot/ChatbotContent.tsx, src/components/chatbot/ChatbotInput.tsx, src/components/chatbot/ChatbotMain.tsx, src/components/headers/HeadersNav.tsx, src/components/recent/NoData.tsx, src/components/recent/Recent.tsx, src/components/search/DeleteSearch.tsx, src/components/search/FindNews.tsx, src/components/search/FindStock.tsx, src/components/search/FindStockItem.tsx, src/components/search/InputItem.tsx, src/components/search/MoreData.tsx, src/components/search/NewsItem.tsx, src/components/search/NoSearchData.tsx, src/components/search/NotFind.tsx, src/components/search/PopularSearch.tsx, src/components/search/RecentSearch.tsx, src/components/shared/Card.tsx, src/utils/date.ts
- Card 국제화 작업
- Search 국제화 작업
- Home 최근조회 및 챗봇 국제화 작업
Close #198
=> feat #198 : Card, Header, Search 국제화 작업

src/app/[locale]/(after)/search/layout.tsx
=> feat #198 : search Layout 추가

src/app/[locale]/(after)/news/page.tsx, src/app/api/news/[id]/route.ts, src/components/news/HomeRecentNews.tsx, src/components/news/HomeRelatedNews.tsx, src/components/news/NewsDetail.tsx, src/components/news/RecentNews.tsx, src/components/news/RelatedNewsToNews.tsx, src/components/news/RelatedNewsToStock.tsx, src/components/shared/Card.tsx, src/components/shared/NewsListItem.tsx, src/service/aightnowClient.ts
=> refact : NewsListItem date변경

src/app/api/search/stock/route.ts
- 한글 검색 추가
Close #209
발견 검색기능에 description_ko에 들어간 것들도 검색할 수 있게 수정.
ex) 클라우드, 미국, 소프트웨어 등등 검색을 해도 검색가능
=> feat #209 : 한글 검색 추가

src/utils/stock.ts
=> fix #213 : formattinPrice 표기 오류 수정

src/components/shared/StockListItem.tsx, src/utils/stock.ts
- stock.ts getStockStyle 추가
- stock.ts compareToZero 삭제
=> refact #221 : StockListItem 삼항 연산자 개선

src/app/api/news/[id]/route.ts
=> fix #223 : 뉴스 조회 수 로직 dayjs utc 에러

src/app/[locale]/(after)/home/page.tsx, src/components/home/AIReport.tsx, src/components/home/ReportWrapper.tsx, src/components/shared/chart/SpecificStockAIReport.tsx, src/service/aightnowClient.ts
#87 #156 #110 
- AI 리포트 배치
- 관심 종목 List 렌더링
=> [#220] 메인 페이지 구조 수정

src/app/api/stock/exchange/route.ts, src/components/shared/ToggleButton.tsx, src/components/stock/StockDescription.tsx, src/components/stock/detail/ChartSection.tsx, src/service/aightnowClient.ts, src/utils/stock.ts
- 한국 수출입은행 API 실시간 환율정보 받기
- 환율 기반 주식가격 계산
- 주식가격 달러 <-> 원화(위안, 엔, 유로) 변환 기능
=> feat #230 : 실시간 환율 정보

messages/en.json, messages/fr.json, messages/ja.json, messages/ko.json, messages/zh.json, src/app/[locale]/(after)/home/page.tsx, src/app/[locale]/(after)/stock/[stockId]/page.tsx, src/app/[locale]/(after)/stock/interest/layout.tsx, src/app/[locale]/(after)/stock/interest/page.tsx, src/components/home/AIReport.tsx, src/components/home/ReportWrapper.tsx, src/components/homefavorite/FavoriteMain.tsx, src/components/shared/chart/SpecificStockAIReport.tsx, src/components/shared/chart/StockAIReportCard.tsx, src/components/shared/chart/StockAIReportChart.tsx, src/components/shared/chart/StockChartCard.tsx, src/components/shared/modal/ModalAddInterest.tsx, src/components/stock/RequestWrapper.tsx, src/components/stock/ThatGoAddInterest.tsx, src/components/stock/detail/ChartSection.tsx, src/components/stock/interest/Popular.tsx, src/components/stock/interest/Recent.tsx, src/components/stock/interest/Searched.tsx
#141, #6, #18, #85, #110, #120, #138, #186, #220
- 다국어 적용
- Chart UI 배치 변경
- 다국어 적용 시 UI 틀어짐 발생
- 소통 후 수정 예정
=> [#228] 담당 Component에 i18n 적용

messages/en.json, messages/fr.json, messages/ja.json, messages/ko.json, messages/zh.json, src/components/stock/StockDescription.tsx, src/components/stock/detail/AddInterest.tsx, src/components/stock/detail/ChartSection.tsx
#228 
- ChartSection 컴포넌트 충돌 해결
=> fix #233: ChartSection 컴포넌트 충돌 해결

package.json, src/app/api/chatbot/route.ts, src/components/chatbot/ChatbotChat.tsx, src/components/chatbot/ChatbotContent.tsx, src/components/chatbot/ChatbotInput.tsx, src/components/chatbot/ChatbotItem.tsx, src/components/skeleton/chatbot/SkeletonChatbotContent.tsx, src/utils/openai.ts, yarn.lock
- openai gpt-4o  적용
- 스켈레톤 적용
Close #215
=> feat #215 : chatbot openai 연결 및 스켈레톤 적용

src/components/stock/StockDescription.tsx
=> feat #230 : 가격 DB 가격 반영

src/app/api/stock/exchange/route.ts
=> refact #245 : 환율 api 코드 개선

messages/en.json, messages/fr.json, messages/ja.json, messages/ko.json, messages/zh.json, src/app/[locale]/(after)/stock/layout.tsx
=> refact #249 : Stock 페이지 metadata 추가

src/app/[locale]/(after)/user/layout.tsx, src/app/[locale]/(before)/layout.tsx, src/components/user/SectionAccount.tsx, src/components/user/SocialWithdrawal.tsx, src/components/user/Withdrawal.tsx, src/components/user/WithdrawalForm.tsx, src/hooks/user/useUpdatePw.ts
#251 
-  user/layout에  metatadata 추가
- 회원삭제 기능 폼 수정
=> 마이페이지 metatadata 추가

src/app/api/chatbot/route.ts, src/components/chatbot/ChatbotContent.tsx, src/components/chatbot/ChatbotInput.tsx, src/components/search/InputItem.tsx, src/utils/openai.ts
- 챗봇 프롬프트 수정
- detailed_data 전달
- ChatbotContent 정규 표현식 적용
- search css 속성 수정
=> feat #256 : 챗봇 프롬프트 수정 및 최신 데이터 전달

src/utils/stock.ts
- ratio 계산 방식 수정 100 곱하는 식  삭제
=> fix #260 : ratio 계산 방식 수정

src/components/shared/StockListItem.tsx
=> refact #266 : StockListItem 문자 정렬

src/app/api/home/recent/route.ts, src/app/api/search/popular/route.ts, src/app/api/stock/ai-report/route.ts, src/components/home/ReportWrapper.tsx, src/components/search/InputItem.tsx, src/components/search/PopularSearch.tsx, src/components/shared/StockListItem.tsx, src/components/shared/chart/SpecificStockAIReport.tsx, src/components/shared/chart/StockAIReportCard.tsx, src/components/shared/chart/StockAIReportChart.tsx, src/components/shared/chart/rechart/MetricsPercent.tsx, src/components/shared/chart/rechart/StockAIReportCore.tsx, src/components/shared/chart/types.d.ts, src/components/stock/detail/AddInterest.tsx, src/components/stock/detail/ChartSection.tsx, src/hooks/useGetChartData.tsx, src/service/aightnowClient.ts
#243, #220, #235 
- Chart 데이터 점수제 변경
- 주가, 투자지수, 수익성, 성장성, 관심도 데이터를 퍼센티지에서 점수제로 변경
- 이를 통해 각 데이터의 점수화를 통해 보다 직관적인 비교가 가능
-  Stock Detail 페이지 진입 시 조회수 자동 증가 API 로직 추가
- 'StockListItem' 컴포넌트의 onClick 이벤트에 따른 조회수 증가 로직 제거 
-  Stock Detail 페이지에서 관심종목 해제 버튼 hover 시 색상 변경
=> [#265] 1차 QA 피드백 반영

next.config.mjs, src/components/shared/NewsListItem.tsx
- 뉴스 이미지 sizes 옵션 추가
- next config의 images에 format 추가
=> release #274 : News 이미지 최적화

src/components/search/NewsItem.tsx, src/components/shared/Card.tsx
- Card 최적화
- Search_News 최적화
Close #277
=> refact #277 : 이미지 최적화

src/app/[locale]/(after)/user/layout.tsx, src/components/shared/ProfileDetails.tsx, src/components/signup/Popup.tsx, src/components/signup/ProfileImageEditor.tsx, src/components/skeleton/mypage/SkeletonSidebar.tsx, src/components/user/CommonSection.tsx, src/components/user/ConfirmCanclePopup.tsx, src/components/user/LanguageSection.tsx, src/components/user/ProfileUpdated.tsx, src/components/user/SidebarItem.tsx, src/components/user/SocialWithdrawal.tsx, src/components/user/UserAccountEdit.tsx, src/components/user/UserAccountForm.tsx, src/components/user/UserProfile.tsx, src/components/user/Withdrawal.tsx
#281 
- sidebar 컴포넌트 layout에서 dynamic import 적용, SkeletonSidebar 작성
-  next/image 최적화, priority, sizes, fill 속성 적용
- button, link 태그 aria-label 적용
=> refact #281 : 마이페이지 이미지, aria-label, sidebar 최적화

messages/en.json, messages/fr.json, messages/ja.json, messages/ko.json, messages/zh.json, src/components/news/RelatedStock.tsx
=> 뉴스 관련 주식 없을 때 UI 추가

src/components/skeleton/shared/SkeletonWrapper.tsx, src/components/stock/ShowingInterest.tsx
=> 관심종목 스켈레톤 UI 수정

src/components/shared/StockIcon.tsx, src/components/shared/StockListItem.tsx
- StockIcon alt 추가 - 접근성 향상
- StockIcon alt 추가 - 접근성 향상
=> refact #294 : StockIcon alt 추가

src/app/api/chatbot/route.ts, src/components/chatbot/ChatbotChat.tsx, src/components/chatbot/ChatbotContent.tsx, src/store/chatbotStore.ts
=> feat #293 : 챗봇 기록 삭제 추가

messages/en.json, messages/fr.json
=> refact #297 : 차트 지표 약어로 수정

src/app/[locale]/(after)/home/page.tsx, src/app/[locale]/(after)/stock/interest/page.tsx, src/components/home/AIReport.tsx, src/components/home/ReportWrapper.tsx, src/components/homefavorite/FavoriteItem.tsx, src/components/homefavorite/FavoriteMain.tsx, src/components/shared/StockListItem.tsx, src/components/shared/modal/ModalAddInterest.tsx, src/components/stock/RequestWrapper.tsx, src/components/stock/detail/ChartSection.tsx, src/components/stock/interest/Searched.tsx, src/service/aightnowClient.ts, src/service/httpClient.ts, src/service/serviceType.d.ts
#243, #220, #186 
- 주식 가격 실시간 조회
- 관심 종목 추가/삭제 시 Home 반영
- 주식 종목의 이름을 영어로 변경
- Chart 점수의 NaN 데이터 수정
=> [#287] 1차 QA Issue2 피드백

src/components/chatbot/ChatbotChat.tsx, src/components/chatbot/ChatbotContent.tsx, src/components/chatbot/ChatbotInput.tsx
=> refact #302 : 챗봇 스켈레톤 수정

src/components/recent/NoData.tsx, src/components/search/NotFind.tsx
=> refact #304 : 폰트 수정

src/components/user/ProfileUpdated.tsx, src/components/user/UserAccountEdit.tsx, src/components/user/UserAccountForm.tsx
#306 
- 정보 수정 시 변경 값 없다면 수정 불가
=> feature #306 : 마이페이지 수정

src/components/stock/StockDescription.tsx, src/utils/stock.ts
=> comparePrice 환율 미반영

src/components/shared/Card.tsx
=> feat #311 : Card Link 경로 수정

src/components/stock/RequestWrapper.tsx, src/components/stock/detail/ChartSection.tsx
#243, #235, #186 
- pollingInterval 대체 시간 7000ms로 수정
- 관심 종목 대체 UI
- 요약 보고서 한/영 버전 반영
- 요약 보고서의 한/영 버전 반영은 디스코드 회의를 위한 임시 반영
=> [#308] 소통을 위한 2차 QA 피드백 반영

src/components/shared/NewsListItem.tsx
=> fix #319 : 뉴스 이미지 없을 때 배경색 수정
